Update submit script for adios2_stream on Polaris

diff --git a/examples/adios2_stream/qsub_polaris b/examples/adios2_stream/qsub_polaris
--- a/examples/adios2_stream/qsub_polaris
+++ b/examples/adios2_stream/qsub_polaris
@@ -15,7 +15,7 @@ echo "#!/bin/bash -l" > $SFILE
 echo "#PBS -S /bin/bash" >>$SFILE
 echo "#PBS -N adios2_example" >>$SFILE
 echo "#PBS -l select=${NODES}" >>$SFILE
-echo "#PBS -l walltime=${TIME}" >>$SFILE
+echo "#PBS -l walltime=${TIME}:00" >>$SFILE
 echo "#PBS -l filesystems=home:eagle" >>$SFILE
 echo "#PBS -A datascience" >>$SFILE
 echo "#PBS -q ${QUEUE}" >>$SFILE
@@ -29,20 +29,37 @@ echo -e "\necho Jobid: \$PBS_JOBID" >>$SFILE
 echo "echo Running on host \`hostname\`" >>$SFILE
 echo "echo Running on nodes \`cat \$PBS_NODEFILE\`" >>$SFILE
 
+py_version=`python --version`
+parsed_version=$(echo ${py_version#Python } | awk -F. '{print $1"."$2}')
+echo -e "\n# Set ADIOS2 library" >>$SFILE
+echo "ADIOS2_LIBS="NEKRS" # options are NEKRS, SYSTEM" >>$SFILE
+echo "if [ \"\$ADIOS2_LIBS\" = "SYSTEM" ]; then" >>$SFILE
+echo "    module load spack-pe-base/0.8.1" >>$SFILE
+echo "    module load adios2/2.10.0-cuda" >>$SFILE
+echo "    export FABRIC_PROVIDER=cxi" >>$SFILE
+echo "    export FABRIC_IFACE=cxi0" >>$SFILE
+echo "elif [ \"\$ADIOS2_LIBS\" = "NEKRS" ]; then" >>$SFILE
+echo "    export PYTHONPATH=\$PYTHONPATH:${NEKRS_HOME}/lib/python${parsed_version}/site-packages" >> $SFILE
+echo "fi" >> $SFILE
 echo "module use /soft/modulefiles/" >> $SFILE
 echo "module load ${FRAMEWORKS_MODULE}" >> $SFILE
 echo "conda activate" >> $SFILE
 echo "module list" >> $SFILE
 
 echo -e "\n# Compute number of ranks" >> $SFILE
-echo "NODES=\$(cat \$PBS_NODEFILE | wc -l)" >> $SFILE
-echo "RANKS=\$(( NODES * $RANKS_PER_NODE ))" >> $SFILE
+echo "RANKS_PER_NODE=$RANKS_PER_NODE" >> $SFILE
+echo "TOT_NODES=\$(cat \$PBS_NODEFILE | wc -l)" >> $SFILE
+echo "if [ \$((TOT_NODES % 2)) -ne 0 ]; then" >> $SFILE
+echo "    echo \"Error: Need even number of nodes, got \$TOT_NODES\"" >> $SFILE
+echo "    exit 1" >> $SFILE
+echo "fi" >> $SFILE
+echo "COMPONENT_NODES=\$((TOT_NODES / 2))" >> $SFILE
+echo "RANKS=\$(( COMPONENT_NODES * RANKS_PER_NODE ))" >> $SFILE
+echo "head -n \$COMPONENT_NODES \$PBS_NODEFILE > sim_hostfile" >> $SFILE
+echo "tail -n \$COMPONENT_NODES \$PBS_NODEFILE > trainer_hostfile" >> $SFILE
 
-py_version=`python --version`
-parsed_version=$(echo ${py_version#Python } | awk -F. '{print $1"."$2}')
 echo -e "\n# ADIOS2 vars" >> $SFILE
 echo "export MPICH_GPU_SUPPORT_ENABLED=0" >> $SFILE
-echo "export PYTHONPATH=\$PYTHONPATH:${NEKRS_HOME}/lib/python${parsed_version}/site-packages" >> $SFILE
 echo "#export SstVerbose=1" >> $SFILE
 echo "export OMP_PROC_BIND=spread" >> $SFILE
 echo "export OMP_PLACES=threads" >> $SFILE
@@ -57,9 +74,16 @@ echo "    echo Cleaning up old .bp files" >> $SFILE
 echo "    rm -r ./*.bp" >> $SFILE
 echo "fi" >> $SFILE
 
+echo -e "\n# Setup run" >>$SFILE
+echo "CPU_BIND=\"list:24:16:8:1\"" >>$SFILE
+echo "NUM_PTS=60000" >>$SFILE
+echo "MODE=sync" >>$SFILE
+echo "TRANSPORT=RDMA" >>$SFILE
+echo "IO_MODE=posix" >>$SFILE
+
 echo -e "\n# Run" >>$SFILE
-echo "mpirun -np \$RANKS --ppn $RANKS_PER_NODE ./sim &" >> $SFILE
-echo "mpirun -np \$RANKS --ppn $RANKS_PER_NODE python trainer.py" >> $SFILE
+echo "mpirun -np \$RANKS --ppn \$RANKS_PER_NODE --cpu-bind \$CPU_BIND --hostfile ./sim_hostfile ./sim \$NUM_PTS \$MODE \$TRANSPORT \$IO_MODE &" >> $SFILE
+echo "mpirun -np \$RANKS --ppn \$RANKS_PER_NODE --cpu-bind \$CPU_BIND --hostfile ./trainer_hostfile python trainer.py --data_plane \$TRANSPORT --io_mode \$IO_MODE" >> $SFILE
 echo "wait" >> $SFILE
 chmod u+x $SFILE
 
